services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  ollama:
    external: true
